"use client";
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Twitter, Facebook, Linkedin, Mail, Copy, Info } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { useSession } from "next-auth/react";

const ReferralsPage = () => {
  const [email, setEmail] = useState("");
  const { data: session, status } = useSession();

  const handleInvite = () => {
    console.log("Inviting:", email);
    setEmail("");
  };

  const copyReferralLink = () => {
    // get base url from browser
    const referralCode = session.user.referralCode;
    const baseUrl = window.location.origin;

    navigator.clipboard.writeText(`${baseUrl}/register?ref=${referralCode}`);
    console.log("Referral link copied to clipboard");
  };

  return (
    <div className="min-h-screen bg-white p-8">
      <div className="max-w-6xl mx-auto">
        <h1 className="text-3xl font-bold mb-8 text-gray-900 ">Referrals</h1>

        <Card className="bg-gray-50  mb-8 shadow-sm">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-gray-800 ">
              Grow the BasedAgent community and earn rewards:
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex space-x-2 mb-4">
              <Input
                type="email"
                placeholder="Enter email of the person you want to invite"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="bg-white  text-gray-800  flex-grow"
              />
              <Button
                onClick={handleInvite}
                className="bg-blackCustom border-2 border-blackCustom rounded-none hover:bg-brownCustom text-white"
              >
                <Mail className="mr-2 h-4 w-4" /> Invite
              </Button>
            </div>
            <div className="flex space-x-2 mb-4">
              <Button
                variant="outline"
                size="icon"
                className="bg-blackCustom hover:bg-brownCustom rounded-none border-2 border-black text-white"
              >
                <Twitter className="h-4 w-4 text-white" />
              </Button>
              <Button
                variant="outline"
                size="icon"
                className="bg-blackCustom hover:bg-brownCustom rounded-none border-2 border-black text-white"
              >
                <Facebook className="h-4 w-4 text-white" />
              </Button>
              <Button
                variant="outline"
                size="icon"
                className="bg-blackCustom hover:bg-brownCustom rounded-none border-2 border-black text-white"
              >
                <Linkedin className="h-4 w-4 text-white " />
              </Button>
              <Button
                onClick={copyReferralLink}
                className="bg-blackCustom hover:bg-brownCustom rounded-none border-2 border-black text-white flex-grow"
              >
                <Copy className="mr-2 h-4 w-4" /> Copy referral link
              </Button>
            </div>
            <p className="text-sm text-gray-600 ">
              Earn 10% of the trading fees generated by users you onboard (terms
              and conditions apply).
            </p>
          </CardContent>
        </Card>

        <Card className="bg-gray-50  shadow-sm">
          <CardHeader>
            <div className="flex flex-col gap-3 md:flex-row justify-between">
              <CardTitle className="text-2xl font-bold text-gray-800  flex justify-between items-center">
                Your Referrals
              </CardTitle>
              <Input
                placeholder="Filter referrals"
                className="max-w-sm bg-white  text-gray-800 "
              />
            </div>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="text-gray-600  font-bold">
                    Wallet
                  </TableHead>
                  <TableHead className="text-gray-600  font-bold">
                    Status
                  </TableHead>
                  <TableHead className="text-gray-600  font-bold">
                    SOL
                  </TableHead>
                  <TableHead className="text-gray-600  font-bold">
                    Invite Date
                  </TableHead>
                  <TableHead className="text-gray-600  font-bold">
                    Source
                  </TableHead>
                  <TableHead className="text-gray-600  font-bold">
                    Github Access
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Info className="inline-block ml-1 h-4 w-4 text-gray-400  cursor-help" />
                        </TooltipTrigger>
                        <TooltipContent className="bg-white  text-gray-800  border border-gray-200 ">
                          <p>
                            Level of access granted to the GitHub repository
                          </p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </TableHead>
                  <TableHead className="text-gray-600  font-bold">
                    Actions
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="text-gray-800 ">
                    0x1234...5678
                  </TableCell>
                  <TableCell className="text-green-600 ">Active</TableCell>
                  <TableCell className="text-gray-800 ">3</TableCell>
                  <TableCell className="text-gray-800 ">
                    5 September 2024
                  </TableCell>
                  <TableCell className="text-gray-800 ">
                    X, twitter, LinkedIn
                  </TableCell>
                  <TableCell className="text-gray-800 ">Level 1</TableCell>
                  <TableCell></TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="text-gray-800 ">
                    0xabcd...efgh
                  </TableCell>
                  <TableCell className="text-yellow-600 ">Pending</TableCell>
                  <TableCell className="text-gray-800 ">-</TableCell>
                  <TableCell className="text-gray-800 ">
                    5 September 2024
                  </TableCell>
                  <TableCell className="text-gray-800 ">Email</TableCell>
                  <TableCell className="text-gray-800 ">Level 1</TableCell>
                  <TableCell>
                    <Button
                      size="sm"
                      className="bg-blackCustom hover:bg-brownCustom rounded-none border-2 border-black text-white "
                    >
                      Resend Invite
                    </Button>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        <div className="mt-8 text-right">
          <p className="text-xl font-bold text-gray-800 ">
            Total Earnings: 3 SOL
          </p>
        </div>
      </div>
    </div>
  );
};

export default ReferralsPage;
